logging:
    level:
        root: INFO
        com:
            cyb:
                spring:
                    boot:
                        demo: DEBUG
mybatis:
    type-aliases-package: com.cyb.spring.boot.demo.domain
    mapper-locations: "classpath*:mybatis/com/cyb/spring/boot/demo/core/persistence/*.xml"
             
spring:
    datasource:
        url: jdbc:mysql://localhost/test?useUnicode=true&characterEncoding=UTF-8&useSSL=true
        username: admin
        password: 123
        driver-class-name: com.mysql.jdbc.Driver
        max-active: 10
        max-idle: 5
        min-idle: 0
    redis:
        database: 0
        host: localhost
        port: 6379
        password:
        pool:
            max-active: 8
            max-wait: -1
            max-idle: 8
            min-idle: 0
            timeout: 0
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        virtualHost: /

cyb:
    rabbitmq:
        queue:
            value: cyb-value-queue
            student: cyb-student-queue
        exchange: cyb-exchange
        route-key:
            value: cyb-value-route-key
            student: cyb-student-route-key
    schedule:
        task1:
            cron: "*/10 * * * * ?"